server:
  port: 52000

wind-bot:
  ont-bot-11:
    bots:
      - autoStart: true
        self-id: 355242685
        plat-form: qq
        agreement: OneBot11
        receive-connect-type: WS
        send-connect-type: WS
        ws-host: ws://127.0.0.1:3001
  cmd-prefix: "#"

DB_HOST: 101.33.232.217
DB_PORT: 3306
DB_NAME: wind
DB_USER: root
DB_PWD: PXZ83YeKDLrGL3kh

spring:
  application:
    name: wind
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      maximum-pool-size: 5